---
#Deploy grafana to an openshift cluster 

- name: Create a k8s namespace
  k8s:
    name: monitoring
    api_version: v1
    kind: Namespace
    state: "{{ state }}"

#- name: Create a persistent storage for the grafana configuration 
#  k8s:
#    state: "{{ state }}"
#    definition: "{{ lookup('template', '{{ role_path }}/templates/persistent-volume-grafana.yml') }}"

- name: Create a Deployment by reading the definition from a local file
  k8s:
    state: "{{ state }}"
    force: yes
    definition: "{{ lookup('template', '{{ role_path }}/templates/deployment-grafana.yml') }}"

- name: Create a Service object by reading the definition from a file
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', '{{ role_path }}/templates/service-grafana.yml') }}"

- name: Create a route object by reading the definition from a file
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', '{{ role_path }}/templates/route-grafana.yml') }}"

- name: "Wait for grafana to come up"
  uri:
    url: "{{ grafana_base_url }}/login"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 10
  delay: 5

- name: Get all existing datasources
  uri:
    url: "{{ grafana_base_url }}/api/datasources"
    user: "{{ grafana_username }}"
    password: "{{ grafana_password }}"
    method: GET
    force_basic_auth: true
    status_code: 200
  register: grafana_datasources

- name: Create datasource list from json
  set_fact:
    grafana_datasources_list: "{{ grafana_datasources.json | json_query('[*].name') }}"
      
- name: Delete all existing datasources
  uri:
    url: "{{ grafana_base_url }}/api/datasources/name/{{ item }}"
    user: "{{ grafana_username }}"
    password: "{{ grafana_password }}"
    method: DELETE
    force_basic_auth: true
    status_code: 200
  loop: "{{ grafana_datasources_list }}"

- name: Create grafana datasources
  uri:
    url: "{{ grafana_base_url }}/api/datasources"
    user: "{{ grafana_username }}"
    password: "{{ grafana_password }}"
    method: POST
    body: "{{ lookup('file', item) }}"
    force_basic_auth: true
    status_code: 200
    body_format: json
  with_fileglob:
    - "{{ role_path }}/files/grafana/datasources/*.json"

- name: Create grafana dashboard
  uri:
    url: "{{ grafana_base_url }}/api/dashboards/db"
    user: "{{ grafana_username }}"
    password: "{{ grafana_password }}"
    method: POST
    body: "{{ lookup('file', item) }}"
    force_basic_auth: true
    status_code: 200
    body_format: json
  with_fileglob:
    - "{{ role_path }}/files/grafana/dashboards/*.json"

- name: Set default dashboard
  uri:
    url: "{{ grafana_base_url }}/api/org/preferences"
    user: "{{ grafana_username }}"
    password: "{{ grafana_password }}"
    method: PUT
    body: '{"homeDashboardId":1}'
    force_basic_auth: true
    status_code: 200
    body_format: json

