- name: Create a k8s namespace
  k8s:
    name: monitoring
    api_version: v1
    kind: Namespace
    state: "{{ state }}"

- name: Create a config-map for the prometheus configuration 
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', '{{ role_path }}/templates/config-map-prometheus.yml') }}"

- name: Create a Deployment by reading the definition from a local file
  k8s:
    state: "{{ state }}"
    force: yes
    definition: "{{ lookup('template', '{{ role_path }}/templates/deployment-prometheus.yml') }}"

- name: Create a Service object by reading the definition from a file
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', '{{ role_path }}/templates/service-prometheus.yml') }}"

- name: Create a route object by reading the definition from a file
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', '{{ role_path }}/templates/route-prometheus.yml') }}"