# ALL VARIABLES ARE DOCUMENTED IN THE README

all:
  vars:
    app_server_address: "10.1.20.11"

  children:
    servers:
      hosts:
        10.1.1.5:
          ansible_connection: ssh
          ansible_user: "ubuntu"
          ansible_become: true
          ansible_ssh_private_key_file: "/path/to/privatekeyfile"
          add_ubuntu_interface: true
          app_server_gateway: "10.1.20.1"

    big_ips:
      hosts:
        10.1.1.6:
          provider:
            server: "{{ inventory_hostname }}"
            server_port: "443"
            user: admin
            password: admin
            validate_certs: false
            transport: "rest"
          bigip_domain: "openshift.example.com"
          bigip_hostname: "ip-{{ inventory_hostname_short | replace('.', '-')}}.{{ bigip_domain }}"
          bigip_ntp_server: "\"0.pool.ntp.org\", \"1.pool.ntp.org\""
          bigip_ntp_timezone: "America/Los_Angeles"
          bigip_dns_server: "\"8.8.8.8\""
          bigip_dns_search: "\"{{ bigip_domain }}\""
          bigip_external_self_ip: "10.1.10.241/24"
          bigip_internal_self_ip: "10.1.20.241/24"
          juiceshop_virtual_address: "10.1.10.20"
          log_pool: "10.1.20.9"

          # BIG-IP license key. Only declare this variable if you desire the licensing task in Declarative Onboarding to run.
          # bigip_license: "AAAAA-BBBBB-CCCCC-DDDDD-EEEEEEE"
